### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by johnbeathe** [BenAAndrew/Voice-Cloning-App#102]
No audio clips could be generated, Exception in thread - Thread-9

**Comment by johnbeathe** [comment]
More information about my problem. I used a 10 second .wav file and a text file with about 30 words. This all appeared at the end just before stopping. My system is not connected to the internet.

...
INFO:socketio.server:emitting event "progress" to all [/voice]
INFO:voice:Progress - 4/4
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
INFO:voice:Matched 0 segments
emitting event "error" to all [/voice]
INFO:socketio.server:emitting event "error" to all [/voice]
Exception in thread Thread-9:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "application\utils.py", line 66, in background_task
  File "application\utils.py", line 62, in background_task
  File "dataset\create_dataset.py", line 89, in create_dataset
  File "dataset\create_dataset.py", line 85, in create_dataset
  File "dataset\clip_generator.py", line 366, in clip_generator
AssertionError: No audio clips could be generated

**Comment by BenAAndrew** [comment]
This issue is likely due to an issue with your source audio & text. Please ensure your source meets the criteria here first: https://benaandrew.github.io/Voice-Cloning-App/dataset/#verify-your-source

**Comment by johnbeathe** [comment]
I have tried many different variations using WAV and MP3 with the same result. Is it possible you might consider posting or sending a text and audio file that works so that I can determine how mine are different? I know I am missing something simple but am not able to determine what from the documentation link you sent. Thanks.

**Comment by johnbeathe** [comment]
I have installed the software and am trying to synthesize an audio clip. I get this error on each try "AttributError: Tensor object has no attribute 'repeat_interleave'''. I am using Python3.7 and torch 1.10.1 is installed. Do you have any suggestion why this is occurring?
I have opened an audio file and clicked on "Synthesize and vocode".

**Comment by DoubleF3lix** [comment]
Try using 3.6 as the README says. Just a shot.

**Comment by BenAAndrew** [comment]
Please ensure both the Python version is 3.6 and all your packages match those in `requirements.txt`

**Comment by johnbeathe** [comment]
I have done as you suggested and now it's working fine. Thanks!
