### ISSUE TITLE
Does the app output Tacotron2 models or custom models

### ISSUE THREAD

**Issue by PinkTurkey0** [BenAAndrew/Voice-Cloning-App#111]
When you are importing a model it says to import tacotron2 based models or models generated by this app
Does this output tacotron2 models or a different type?

![image](https://user-images.githubusercontent.com/95888762/156329694-40ddadc9-dbd3-4eca-8bd5-d65854456186.png)

**Comment by BenAAndrew** [comment]
Hi @PinkTurkey0,

This app does output tacotron2 models. I'll change this sentence so that it makes more sense
