### ISSUE TITLE
AssertionError: Output folder already exists

### ISSUE THREAD

**Issue by samueldinesh** [BenAAndrew/Voice-Cloning-App#112]
Error when import dataset again when same dataset during import it is partially closed previously on half run

Error raised as below,
Type: AssertionError
Text: Output folder already exists
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 492, in upload_dataset AssertionError: Output folder already exists

**Comment by BenAAndrew** [comment]
@samueldinesh This means you already have a dataset with the same name you're trying to create the new one with. 
Please give your new dataset a different name

**Comment by BenAAndrew** [comment]
Closing as question has been answered
