### ISSUE TITLE
Invalid characters in text

### ISSUE THREAD

**Issue by AntonDreamer** [BenAAndrew/Voice-Cloning-App#115]
Hello, I trying train Russian speech model, but there are one problem: I can't start training, it says me“invalid characters in text(for alphabet)…”
I downloaded ready to use alphabet but.. What the problem?
In console it displays me English letters but I don't using it

**Comment by BenAAndrew** [comment]
This means you have some invalid characters in the metadata.csv of your dataset. You need to replace the listed characters with valid ones. Same issue https://github.com/BenAAndrew/Voice-Cloning-App/issues/93

**Comment by BenAAndrew** [comment]
Closing as a duplicate issue
