### ISSUE TITLE
Train manual created/imported Dataset: Type Error in Replica1 on Device 1

### ISSUE THREAD

**Issue by SandUhrGucker** [BenAAndrew/Voice-Cloning-App#122]
Hi,

I did the Setup as described in the Documentation.
Used pretrained Model "German STT v0.9.0	German	Aashish Agarwal	Coqui STT v1.0.0	v0.9.0" and Model+config.

**Import works without Error. But when I start Training, this Error occur:**
![Screenshot](https://i.ibb.co/VjbgRt9/Screenshot-17-04-2022-00-22-39.jpg)

I tried without german umlauts with english default, but the error remain.

Here you can download a limited copy (only 2 wavs) of this Dataset: [MinimalDataset](https://drive.google.com/file/d/1LW3UshZyGJp7548oRsjZ_hXnE5MDY0f3/view?usp=sharing)

Could you please give me a Hint?

Regards
Rene

**Comment by SandUhrGucker** [comment]
Oh, Problem found. When I disable Multi-GPU the Error doesnt exists.

I have:
AMD Ryzen 5 APU
Nvidia K80
Nvidia K80

**Comment by BenAAndrew** [comment]
Hi @SandUhrGucker, unfortunately, the multi-GPU support is unstable. It is also not possible to select which GPU to use currently. I've added this idea to the board (https://trello.com/c/Oy1FfsPx/34-denoiser-support) but I doubt it will be investigated unless more people request it
