### ISSUE TITLE
Target Language Not Present in https://coqui.ai/models

### ISSUE THREAD

**Issue by Oct4Pie** [BenAAndrew/Voice-Cloning-App#126]
I was wondering how should I proceed if I can't find the languages I want in https://coqui.ai/models? How do I begin training? How would I train the STT if I wanted to add languages to https://coqui.ai/models? Any specific procedures?

**Comment by BenAAndrew** [comment]
Unfortunately, you'll need to add a Deepspeech voice model for your language to generate a dataset (if not English, German or Spanish). 

If this is not available you'll need to [create the dataset manually](https://benaandrew.github.io/Voice-Cloning-App/dataset/#manually-creating-a-dataset).

You can then add the language by creating an alphabet.txt file (like other languages) but you won't need the Deepspeech model as this is only used for the dataset generation step.

**Comment by Oct4Pie** [comment]
Thanks for the clear response, @BenAAndrew. If I want to train a deepspeech model anyway, do you have a recommended method for the app? I saw coqui STT, but it seems it is going to take a very long time.

**Comment by BenAAndrew** [comment]
I know nothing about how to create a Deepspeech model, sorry. 
If you are planning on doing a one-off I would just create the dataset manually (it's not quick, but might be quicker than creating a Deepspeech model)

**Comment by Oct4Pie** [comment]
Thank you. I will proceed with the manual dataset.
