### ISSUE TITLE
Will there be a CPU mode in the future?

### ISSUE THREAD

**Issue by TecnoEnigmatico** [BenAAndrew/Voice-Cloning-App#127]
I don't have a video card with those features. i would like to know if in the future the program will have support for a mode with CPU.

this program seems the simplest of the ones I've seen.  and I really would like to try it.

i know this is not going in this place. but I don't find a dialogue section like in other projects.

**Comment by BenAAndrew** [comment]
Hi @TecnoEnigmatico,

Yes, a CPU-only version is available for each release. The only difference is you have to use [remote training](https://benaandrew.github.io/Voice-Cloning-App/training/#remote-training) on the training step.

Hope that helps
