### ISSUE TITLE
File already exists but shouldn't

### ISSUE THREAD

**Issue by BartAgterbosch** [BenAAndrew/Voice-Cloning-App#130]
Every time I run the program it will generate a folder called _MEI followed by some numbers in Local/Temp, takes up roundabout 1.6gb each and it will contain some pytorch data by the looks of it.
The odd thing is, that it's the app that generates these folders upon starting, but then immediately throws a warning message that torch/_C.cp36-win_amd64.pyd already exists, but shouldn't.
Even though it generates that file itself every time it runs. 
Beyond that no matter what I throw at it I'm never able to generate any audio clips, it will throw an exception at line 84, perhaps it's related, I have only tried the binary release so far

**Comment by BenAAndrew** [comment]
Hi @BartAgterbosch, this unfortunately is an issue with pyinstaller. It creates a folder in temp for the application which does not get cleaned up if you click close on the app window (I think you have to press ctrl+c to get it to exit properly), so I added a workaround which is supposed to delete old temp folders on startup: https://github.com/BenAAndrew/Voice-Cloning-App/blob/main/main.py#L31

However, I have no idea why this warning message is produced on startup. My guess is that it tries to create the temp folder twice for some reason but I'm not sure.

Regardless, ignore this warning as it has no impact on the app. If you are getting an exception, it is most likely a different issue
