### ISSUE TITLE
Using HIP & HIPIFY tools to port an AMD version

### ISSUE THREAD

**Issue by User202207** [BenAAndrew/Voice-Cloning-App#140]
https://github.com/ROCm-Developer-Tools/HIP

https://github.com/ROCm-Developer-Tools/HIPIFY/

Perhaps an excellent individual can competently use these tools to make Voice-Cloning-App GPU version available to AMD GPU users.

I will try my hand at this, but I am no expert.

Please close this issue if it is done successfully before official feature implementation.

Please post guide to replicate successful executable builds.

**Comment by BenAAndrew** [comment]
Hi @User202207,

Thank you for the suggestion.
Unfortunately Pytorch does not currently support ROCm on Windows and therefore does not support AMD.
When support is added this may be investigated

**Comment by TomieAi** [comment]
have u tried this 

https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows
https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-wsl
