### ISSUE TITLE
Error fetching silero model

### ISSUE THREAD

**Issue by CrazyPlaysHD** [BenAAndrew/Voice-Cloning-App#19]
Full: Traceback (most recent call last): File "C:\Users\superuser\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\superuser\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "C:\Users\superuser\Desktop\Voice-Cloning-App\application\views.py", line 249, in synthesis_post alertnative_words=get_alternative_word_suggestions(audio_path, text), File "C:\Users\superuser\Desktop\Voice-Cloning-App\synthesis\synonyms.py", line 29, in get_alternative_word_suggestions poor_words = evalulate_audio(audio, text) File "C:\Users\superuser\Desktop\Voice-Cloning-App\synthesis\synonyms.py", line 20, in evalulate_audio results = transcribe(audio) File "C:\Users\superuser\Desktop\Voice-Cloning-App\dataset\transcribe.py", line 27, in transcribe repo_or_dir="snakers4/silero-models", model="silero_stt", language="en", device=device File "C:\Users\superuser\Anaconda3\lib\site-packages\torch\hub.py", line 370, in load model = _load_local(repo_or_dir, model, *args, **kwargs) File "C:\Users\superuser\Anaconda3\lib\site-packages\torch\hub.py", line 399, in _load_local model = entry(*args, **kwargs) File "C:\Users\superuser/.cache\torch\hub\snakers4_silero-models_master\hubconf.py", line 25, in silero_stt **kwargs) File "C:\Users\superuser/.cache\torch\hub\snakers4_silero-models_master\utils.py", line 133, in init_jit_model progress=True) File "C:\Users\superuser\Anaconda3\lib\site-packages\torch\hub.py", line 445, in download_url_to_file unit='B', unit_scale=True, unit_divisor=1024) as pbar: File "C:\Users\superuser\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 662, in __init__ TqdmKeyError("Unknown argument(s): " + str(kwargs))) tqdm._tqdm.TqdmKeyError: "Unknown argument(s): {'unit_divisor': 1024}"

**Comment by BenAAndrew** [comment]
Hi @CrazyPlaysHD, have you completed a custom install or are you using the latest executable?

**Comment by CrazyPlaysHD** [comment]
> Hi @CrazyPlaysHD, have you completed a custom install or are you using the latest executable?

i use a new version of this repo.
i synthesize my trained tacotron model and doesnt work

**Comment by BenAAndrew** [comment]
@CrazyPlaysHD did you download the latest release or did you clone the project?

**Comment by CrazyPlaysHD** [comment]
> @CrazyPlaysHD did you download the latest release or did you clone the project?

latest

**Comment by BenAAndrew** [comment]
@CrazyPlaysHD, did you train the model in the app or import it in the "import/export" menu?

**Comment by CrazyPlaysHD** [comment]
> @CrazyPlaysHD, did you train the model in the app or import it in the "import/export" menu?

no i dont train a model from cpu i trained a tacotron model from google colab

**Comment by BenAAndrew** [comment]
I'm not sure I understand. Do you mean that you've trained tacotron2 somewhere else and you are trying to import that model into the app?

**Comment by BenAAndrew** [comment]
@CrazyPlaysHD is this still an issue?

**Comment by BenAAndrew** [comment]
Closing as I don't think this is an issue. Please reopen if it is
