### ISSUE TITLE
Training: list index out of range

### ISSUE THREAD

**Issue by arthur465** [BenAAndrew/Voice-Cloning-App#24]
Hey, when i begin my voice training it will start loading everything then the "list index out of range" message pops up. Can you help me figure out what is the issue please?

`[9084] WARNING: file already exists but should not: C:\Temp\_MEI90842\torch\_C.cp38-win_amd64.pyd
Server initialized for threading.
Server initialized for threading.
pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available.
torchaudio\backend\utils.py:63: UserWarning: The interface of "soundfile" backend is planned to change in 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False` before setting the backend to "soundfile". Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
INFO:matplotlib.font_manager:Generating new fontManager, this may take some time...
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Temp\_MEI90842\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
WARNING:werkzeug:WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:07] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:07] "GET /static/favicon/favicon-16x16.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:11] "GET /train HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:11] "GET /dataset-duration?dataset=Arthur HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:11] "GET /static/favicon/favicon-16x16.png HTTP/1.1" 200 -
Starting Thread
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:17] "POST /train HTTP/1.1" 200 -
486TO-7-EwymZq3MAAAA: Sending packet OPEN data {'sid': '486TO-7-EwymZq3MAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet OPEN data {'sid': '486TO-7-EwymZq3MAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:17] "GET /socket.io/?EIO=4&transport=polling&t=NZZFbi_ HTTP/1.1" 200 -
486TO-7-EwymZq3MAAAA: Received packet MESSAGE data 0/voice,
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Received packet MESSAGE data 0/voice,
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 0/voice,{"sid":"ntZwXJCAwjZ4QntZAAAB"}
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:17] "GET /socket.io/?EIO=4&transport=polling&t=NZZFbjI&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 0/voice,{"sid":"ntZwXJCAwjZ4QntZAAAB"}
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:17] "POST /socket.io/?EIO=4&transport=polling&t=NZZFbjH&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Setting batch size to 16, learning rate to 0.0005. (6GB GPU memory free)"}]
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:22] "GET /socket.io/?EIO=4&transport=polling&t=NZZFbjV&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Setting batch size to 16, learning rate to 0.0005. (6GB GPU memory free)"}]
INFO:voice:Setting batch size to 16, learning rate to 0.0005. (6GB GPU memory free)
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loading model..."}]
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loading model..."}]
INFO:voice:Loading model...
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:22] "GET /socket.io/?EIO=4&transport=polling&t=NZZFcvb&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded model"}]
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:25] "GET /socket.io/?EIO=4&transport=polling&t=NZZFcvj&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded model"}]
INFO:voice:Loaded model
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loading data..."}]
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loading data..."}]
INFO:voice:Loading data...
56 train files, 15 test files
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:25] "GET /socket.io/?EIO=4&transport=polling&t=NZZFdba&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
486TO-7-EwymZq3MAAAA: Sending packet PING data None
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:42] "GET /socket.io/?EIO=4&transport=polling&t=NZZFdbh&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet PING data None
486TO-7-EwymZq3MAAAA: Received packet PONG data
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Received packet PONG data
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:42] "POST /socket.io/?EIO=4&transport=polling&t=NZZFhpw&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded data"}]
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:43] "GET /socket.io/?EIO=4&transport=polling&t=NZZFhpx&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded data"}]
INFO:voice:Loaded data
Epoch: 0
emitting event "progress" to all [/voice]
INFO:socketio.server:emitting event "progress" to all [/voice]
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 0","total":"12000"}]
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 0","total":"12000"}]
INFO:voice:Progress - 0/12000
emitting event "error" to all [/voice]
INFO:socketio.server:emitting event "error" to all [/voice]
486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["error",{"type":"IndexError","text":"list index out of range","stacktrace":"Traceback (most recent call last):\n  File \"application\\utils.py\", line 75, in background_task\n  File \"training\\train.py\", line 128, in train\n  File \"torch\\utils\\data\\dataloader.py\", line 435, in __next__\n  File \"torch\\utils\\data\\dataloader.py\", line 475, in _next_data\n  File \"torch\\utils\\data\\_utils\\fetch.py\", line 44, in fetch\n  File \"torch\\utils\\data\\_utils\\fetch.py\", line 44, in <listcomp>\n  File \"training\\dataset.py\", line 69, in __getitem__\n  File \"training\\dataset.py\", line 37, in get_mel_text_pair\nIndexError: list index out of range\n"}]
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet MESSAGE data 2/voice,["error",{"type":"IndexError","text":"list index out of range","stacktrace":"Traceback (most recent call last):\n  File \"application\\utils.py\", line 75, in background_task\n  File \"training\\train.py\", line 128, in train\n  File \"torch\\utils\\data\\dataloader.py\", line 435, in __next__\n  File \"torch\\utils\\data\\dataloader.py\", line 475, in _next_data\n  File \"torch\\utils\\data\\_utils\\fetch.py\", line 44, in fetch\n  File \"torch\\utils\\data\\_utils\\fetch.py\", line 44, in <listcomp>\n  File \"training\\dataset.py\", line 69, in __getitem__\n  File \"training\\dataset.py\", line 37, in get_mel_text_pair\nIndexError: list index out of range\n"}]
list index out of range
INFO:werkzeug:127.0.0.1 - - [17/Apr/2021 21:30:43] "GET /socket.io/?EIO=4&transport=polling&t=NZZFi21&sid=486TO-7-EwymZq3MAAAA HTTP/1.1" 200 -
486TO-7-EwymZq3MAAAA: Sending packet PING data None
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Sending packet PING data None
486TO-7-EwymZq3MAAAA: Client is gone, closing socket
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Client is gone, closing socket
486TO-7-EwymZq3MAAAA: Client is gone, closing socket
INFO:engineio.server:486TO-7-EwymZq3MAAAA: Client is gone, closing socket
`

**Comment by BenAAndrew** [comment]
Hi @arthur465, This error means that it was not able to load your dataset. Could you firstly tell me whether this was an imported or generated dataset?

**Comment by arthur465** [comment]
Hey, BenAAndrew, it is audio of my voice. I tried to build the dataset again and it seems to process but now I get a long list of could not transcribe errors. I'm pretty sure I did not set something up right but I don't know what it is  How can I fix this?
Coverting data\datasets\Arthur\audio.mp3...
Loading script from data\datasets\Arthur\text.txt...
Searching text for matching fragments...
Changing sample rate...
Fetching segments...
Matching segments...
Generating segments...
Could not transcribe data\datasets\Arthur\wavs\1620_3900.wav

    On Sunday, April 18, 2021, 12:01:27 PM PDT, BenAAndrew ***@***.***> wrote:  
 
 


Hi @arthur465, This error means that it was not able to load your dataset. Could you firstly tell me whether this was an imported or generated dataset?

**Comment by BenAAndrew** [comment]
Hi @arthur465, that means that there is an issue with the generated clips. Please could you go to the file (i.e. `datasets\Arthur\wavs\1620_3900.wav`) in the data folder (found in the same directory as the app) and check that it is playable

**Comment by arthur465** [comment]
So I checked the folder and there is nothing in the wavs folder. However there is another folder temp_wavs. It seems the clips are all in there but they are not playable. All are 0 in length

    On Monday, April 19, 2021, 5:13:34 AM PDT, BenAAndrew ***@***.***> wrote:  
 
 


Hi @arthur465, that means that there is an issue with the generated clips. Please could you go to the file (i.e. datasets\Arthur\wavs\1620_3900.wav) in the data folder (found in the same directory as the app) and check that it is playable

**Comment by BenAAndrew** [comment]
@arthur465, it sounds like something has gone wrong when cutting the clips. Could be an issue with FFmpeg. Perhaps try manually installing FFmpeg? It sounds like the same issue as https://github.com/BenAAndrew/Voice-Cloning-App/issues/11

**Comment by BenAAndrew** [comment]
Closing as this issue appears to be the same as https://github.com/BenAAndrew/Voice-Cloning-App/issues/11. I will continue investigating in that thread

**Comment by BenAAndrew** [comment]
Closing as this issue appears to be the same as https://github.com/BenAAndrew/Voice-Cloning-App/issues/11. I will continue investigating in that thread
