### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by ericstheguy** [BenAAndrew/Voice-Cloning-App#26]
Could support for Google Colab be implemented?
Specifically for GPU limitations and accessibility etc.

**Comment by BenAAndrew** [comment]
@ericstheguy good suggestion. It was something that was tried in an early stage of the project but unfortunately, Google Colab did not provide enough GPU memory to be feasible. If anyone can find a way of making it work however, this would be useful

**Comment by ericstheguy** [comment]
I'm not 100% sure but the install guide to this repo shows that 4GB GPU memory is the minimum. Google colab usually allows up to 11GB with a Tesla T4?

**Comment by ericstheguy** [comment]
Probably not efficient but it can be improved.
https://colab.research.google.com/drive/1jP9jUtXt_hA1e2Upd4uJfYsGD34vbSA6?usp=sharing
(Also from me, who has little to no experience in python.)

**Comment by BenAAndrew** [comment]
@ericstheguy nice work. The issue I had was that colab was sharing the GPU with other notebooks, so although the GPU has 11GB, it wasn't actually giving me that.
