### ISSUE TITLE
Can't transcribe data when building dataset

### ISSUE THREAD

**Issue by ironpanther** [BenAAndrew/Voice-Cloning-App#27]
I have created a text file and MP3 exactly as in the demo, from audible.   The converted wav plays fine when I check it.   But when I try to make a dataset, it gives thousands of errors, and not a single sample is created:

Coverting data\datasets\Kate\audio.mp3...
Loading script from data\datasets\Kate\text.txt...
Searching text for matching fragments...
Changing sample rate...
Fetching segments...
Matching segments...
Generating segments...
Could not transcribe data\datasets\Kate\wavs\0_1110.wav
Could not transcribe data\datasets\Kate\wavs\1110_2760.wav
Could not transcribe data\datasets\Kate\wavs\4260_7020.wav
Could not transcribe data\datasets\Kate\wavs\7440_14220.wav
Could not transcribe data\datasets\Kate\wavs\14220_15330.wav
Could not transcribe data\datasets\Kate\wavs\16410_18060.wav
Could not transcribe data\datasets\Kate\wavs\18390_24120.wav
Could not transcribe data\datasets\Kate\wavs\26670_28800.wav
Could not transcribe data\datasets\Kate\wavs\28860_30300.wav
Could not transcribe data\datasets\Kate\wavs\30690_38610.wav
Could not transcribe data\datasets\Kate\wavs\40110_49170.wav
Could not transcribe data\datasets\Kate\wavs\50490_52020.wav
Could not transcribe data\datasets\Kate\wavs\52080_59490.wav
Could not transcribe data\datasets\Kate\wavs\59490_65670.wav
Could not transcribe data\datasets\Kate\wavs\79080_80940.wav
Could not transcribe data\datasets\Kate\wavs\94380_101730.wav
(and thousands more)   

Error from the .exe window (example)---

INFO:voice:Progress - 5111/5134
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Could not transcribe data\\datasets\\Kate\\wavs\\15369720_15372090.wav"}]
INFO:engineio.server:hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Could not transcribe data\\datasets\\Kate\\wavs\\15369720_15372090.wav"}]
INFO:voice:Could not transcribe data\datasets\Kate\wavs\15369720_15372090.wav
emitting event "progress" to all [/voice]
INFO:socketio.server:emitting event "progress" to all [/voice]
hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 5112","total":"5134"}]
INFO:engineio.server:hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 5112","total":"5134"}]
INFO:voice:Progress - 5112/5134
emitting event "progress" to all [/voice]
INFO:socketio.server:emitting event "progress" to all [/voice]
hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 5113","total":"5134"}]
INFO:engineio.server:hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 5113","total":"5134"}]
INFO:voice:Progress - 5113/5134
INFO:werkzeug:127.0.0.1 - - [20/Apr/2021 22:51:11] "GET /socket.io/?EIO=4&transport=polling&t=NZoZQ3z&sid=hsCGLghog3EenoWEAAAA HTTP/1.1" 200 -
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Could not transcribe data\\datasets\\Kate\\wavs\\15374100_15376590.wav"}]
INFO:engineio.server:hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Could not transcribe data\\datasets\\Kate\\wavs\\15374100_15376590.wav"}]
INFO:voice:Could not transcribe data\datasets\Kate\wavs\15374100_15376590.wav
emitting event "progress" to all [/voice]
INFO:socketio.server:emitting event "progress" to all [/voice]
hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 5114","total":"5134"}]
INFO:engineio.server:hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 5114","total":"5134"}]
INFO:voice:Progress - 5114/5134

Similar errors continue until the last segment. It ends with-----

"INFO:engineio.server:hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Matched 0 segments"}]
INFO:voice:Matched 0 segments
INFO:werkzeug:127.0.0.1 - - [20/Apr/2021 22:51:13] "GET /socket.io/?EIO=4&transport=polling&t=NZoZQSN&sid=hsCGLghog3EenoWEAAAA HTTP/1.1" 200 -
emitting event "error" to all [/voice]
INFO:socketio.server:emitting event "error" to all [/voice]
hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["error",{"type":"AssertionError","text":"No audio clips could be generated","stacktrace":"Traceback (most recent call last):\n  File \"application\\utils.py\", line 75, in background_task\n    func(logging=logger, **kwargs)\n  File \"dataset\\create_dataset.py\", line 16, in create_dataset\n    clip_generator(converted_audio, text_path, forced_alignment_path, output_path, label_path, logging)\n  File \"dataset\\clip_generator.py\", line 86, in clip_generator\n    assert result_fragments, \"No audio clips could be generated\"\nAssertionError: No audio clips could be generated\n"}]
INFO:werkzeug:127.0.0.1 - - [20/Apr/2021 22:51:14] "GET /socket.io/?EIO=4&transport=polling&t=NZoZQVd&sid=hsCGLghog3EenoWEAAAA HTTP/1.1" 200 -
INFO:engineio.server:hsCGLghog3EenoWEAAAA: Sending packet MESSAGE data 2/voice,["error",{"type":"AssertionError","text":"No audio clips could be generated","stacktrace":"Traceback (most recent call last):\n  File \"application\\utils.py\", line 75, in background_task\n    func(logging=logger, **kwargs)\n  File \"dataset\\create_dataset.py\", line 16, in create_dataset\n    clip_generator(converted_audio, text_path, forced_alignment_path, output_path, label_path, logging)\n  File \"dataset\\clip_generator.py\", line 86, in clip_generator\n    assert result_fragments, \"No audio clips could be generated\"\nAssertionError: No audio clips could be generated\n"}]
No audio clips could be generated"

  The script/text is correct, the audio is clear.   I even tried "trimming" the audio and text so that they start at exactly the same time/word, but it still seems unable to transcribe the audio.   I am using Windows 10, with the downloaded app.   (A second issue I notice, is that every time I run the app, is that it installs all the files again to my user/temp folder---this quickly takes up many gigabytes of hard drive space---should it not install the files permanently, just once, to the directory/folders the app is in?)

**Comment by ironpanther** [comment]
I found the sample files in the "tests" folder, and tried them---they didn't work either, so I assume I am somehow missing files/installation problem?   

Coverting data\datasets\Test\audio.mp3...
Loading script from data\datasets\Test\text.txt...
Searching text for matching fragments...
Changing sample rate...
Fetching segments...
Matching segments...
Generating segments...
Could not transcribe data\datasets\Test\wavs\0_2730.wav
Could not transcribe data\datasets\Test\wavs\2820_5100.wav
Could not transcribe data\datasets\Test\wavs\5130_7560.wav
Matched 0 segments

**Comment by BenAAndrew** [comment]
Hi @ironpanther, this issue is the same as https://github.com/BenAAndrew/Voice-Cloning-App/issues/11. I'll post updates there
