### ISSUE TITLE
Imported model cannot be loaded

### ISSUE THREAD

**Issue by ericstheguy** [BenAAndrew/Voice-Cloning-App#33]
Was exporting a model beforehand. (Using a google colab notebook.)

Type: ValueError
Text: invalid literal for int() with base 10: 'checkpoints'
Full: Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/content/Voice-Cloning-App/application/views.py", line 391, in download_model model_path = get_latest_checkpoint(os.path.join(paths["models"], model_name)) File "/content/Voice-Cloning-App/training/checkpoint.py", line 27, in get_latest_checkpoint if int(checkpoint.split("_")[1].split(".")[0]) > int(latest_checkpoint.split("_")[1].split(".")[0]): ValueError: invalid literal for int() with base 10: 'checkpoints'

**Comment by BenAAndrew** [comment]
Hi @ericstheguy, do you mean that you have exported a model from a colab notebook and want to use it in the app?

**Comment by ericstheguy** [comment]
Not really. Generally the error happens whenever I try to do anything with the model. Like training from a 10k iterations checkpoint.

**Comment by BenAAndrew** [comment]
@ericstheguy Do you start with an existing checkpoint that you've imported or is it from scratch?

**Comment by ericstheguy** [comment]
Was using an existing checkpoint trained to 10,000 iterations (Batch Size  = 78)

**Comment by BenAAndrew** [comment]
@ericstheguy Could you upload the checkpoint to google drive and reply with the link so I can verify

**Comment by ericstheguy** [comment]
> @ericstheguy Could you upload the checkpoint to google drive and reply with the link so I can verify

https://drive.google.com/file/d/1MjISOaMuEcsInYbTUJzoKFCCQHtsRy2f

**Comment by BenAAndrew** [comment]
Hi @ericstheguy. I am able to load and use this checkpoint in the app. Could you go into settings and delete your model, then try reimporting it again

**Comment by BenAAndrew** [comment]
@ericstheguy I can synthesize with the model. Are you trying to train or synthesize?

**Comment by ericstheguy** [comment]
Preferably just train it. As it's only just about 1k epochs. Hopefully it's nothing to do with colab.

**Comment by ericstheguy** [comment]
Figured it out, really strange. Just had to import the model into the app with a new name, and import the dataset with the same name as the model.
