### ISSUE TITLE
How to synthesize long texts?

### ISSUE THREAD

**Issue by natowi** [BenAAndrew/Voice-Cloning-App#40]
Is it possible to synthesize longer texts? My audioclips are only 12 seconds long.
I tested a few other open source voice cloning apps, and most skip on the synthesis part and only allow to generate a few seconds of audio. Is it possible to generate minutes, if not hours of audio with this app? If not, can you recommend something? I´m basically looking for an open source tool like Balabolka, but for trained deep learning voice models to actually make use of them.

Great tool btw. :)

**Comment by BenAAndrew** [comment]
Hi @natowi, sorry for the late reply. The model this app uses (tacotron2) is trained on audio of 1-10 seconds and is unable to produce audio outside of that duration range. You can synthesize multiple clips and join them together but this is difficult/time consuming so probably isn't viable.

Sorry about that, hope you find what you are looking for :)

**Comment by natowi** [comment]
Hi @BenAAndrew and thank you for the explanation! 

I´ll keep my eyes open, we are experiencing rapid development in the field, so I am sure we will be able to produce longer audio with open source tools eventually.

**Comment by TheLustriVA** [comment]
Even just a command-line interface for the synthesizer so we can loop it in Python and knit the output files together would be amazing.
