### ISSUE TITLE
No audio with Waveglow vocoder chosen

### ISSUE THREAD

**Issue by RayDAnt3D** [BenAAndrew/Voice-Cloning-App#42]
Noticed that as of version 0.7.5 and onward choosing Waveglow as vocoder in the Windows binary of the App on any trained voice results in a correct looking Mel chart but no audible audio in the accompanying wave file generated.

**Comment by BenAAndrew** [comment]
Investigating now

**Comment by BenAAndrew** [comment]
I'm not sure about release 0.7.5 but in the latest (0.8.1) this appears to work with waveglow. Have you tried that release 
![image](https://user-images.githubusercontent.com/35925918/123675171-53c42b80-d83a-11eb-9e2a-75adeff012d6.png)

**Comment by BenAAndrew** [comment]
It appears to only be an issue in the executable, not in the manual run

**Comment by BenAAndrew** [comment]
The issue was accidentally changing from CUDA 10.2 to 11. I will fix this and create a new release
