### ISSUE TITLE
New Language Support: Training can only handle UTF-8

### ISSUE THREAD

**Issue by brazilgithub** [BenAAndrew/Voice-Cloning-App#44]
After I install my language, I try to train the database, but I get this warning. 

![b1062e87-ae2e-4ee5-a6f2-92b324851660](https://user-images.githubusercontent.com/61645540/124312667-14515400-db46-11eb-938f-0f3acfb6adb0.jpg)

I can only continue the training if I save the csv file in UTF-8, but this makes my language characters all weird. 

![d414b603-5dc0-4f90-b96d-b8f323f6c8e1](https://user-images.githubusercontent.com/61645540/124313796-c2a9c900-db47-11eb-8668-3908dbb53b7a.jpg)

**Comment by BenAAndrew** [comment]
I think I've identified what's been causing this issue and it should now be fixed in the latest commit.
Also, make sure to change the minimum confidence to a lower value (i.e. 0.7) in "Advanced options" on the create dataset page (step 1)

**Comment by BenAAndrew** [comment]
Fixed in recent commit
