### ISSUE TITLE
Force Align text and Audio (dataset)

### ISSUE THREAD

**Issue by vinamramunot-tech** [BenAAndrew/Voice-Cloning-App#5]
Hi @BenAAndrew I am on the step where I am trying to align the text and audio of an audiobook. I have acquired the audio and text from amazon audible. Unfortunately, I was not able to assign the help label to this issue. I don't think I have the permission for that. 

- [X] using virtualenv 

---
> In order to work through align.py, I had to modify it. After modifying I was able to run the file. Below is the modified part of the file. Also in the screenshot category I have mentioned how I am trying to execute this file.

```py
import os
import sys
import json
import logging
import argparse
from pydub import AudioSegment

sys.path.append(".")

from search import FuzzySearch
from audio import DEFAULT_RATE, read_frames_from_file, vad_split
from dataset.transcribe import stt
```
---
# Screenshots

### Failure Point
![failure point](https://user-images.githubusercontent.com/56406734/111528186-38279000-8737-11eb-8963-69bc9242c6b0.PNG)

---
# Questions
1. Do you suggest to use a virtualenv?
2. Do I need to reduce the quality of wav file or the mp3 file?

---
# Link to the dataset
[Audio Dataset](https://drive.google.com/drive/folders/1wTP1fIfXuVbIM98yySo5BS6RCXoz2cjN?usp=sharing)

I have the book.txt and the mp3 file. I have converted that mp3 to wav file when I am trying to use the align.
Please let me know if you can try using my dataset. Thanks for the help in advance.

**Comment by BenAAndrew** [comment]
Hi @vinamramunot-tech, 

Firstly, an interesting bug. I haven't seen that before. I'm a bit confused about why adding '.' to the path would help, I assume there's a file it is not picking up which is causing the error. Was that the only change you made?

Also to answer your questions:
1. I use anaconda environment management for development purposes but that isn't necessary for just using the app
2. The service should be flexible to varying audio but it should convert it to 22050hz 16-bit PCM before processing. I'll check your audio out and see if I get the same issue

**Comment by vinamramunot-tech** [comment]
Actually I was able to proceed further with this issue.

To answer you question for did I change anything else: I did not change anything else other than align.py. This might not be a bug because I am using pip and you are using anaconda. However, something interesting to look into.

To add further regarding the second point which is "service is flexible to varying audio...". I am using this online service https://online-audio-converter.com/ to convert mp3 audio to wav file. I tested on different  `sample rate` and `channels`. However, it only works on `sample rate` as `16000Khz` and `Channels` as `1`.  You are welcome to try it out. Maybe I am producing something wrong on my side.

--- 
## Screenshot

![converter](https://user-images.githubusercontent.com/56406734/111538509-2a780780-8743-11eb-8736-ea76c439b7ae.PNG)

---

Thank you!!

**Comment by vinamramunot-tech** [comment]
This is the current progress while I am running align.py. Will keep you updated if anything else comes up/

![current progress](https://user-images.githubusercontent.com/56406734/111538788-7fb41900-8743-11eb-819b-ff7a3b8295f2.PNG)

**Comment by vinamramunot-tech** [comment]
This is the next thing is that I was able to successfully run for clip_generator.py

![next step](https://user-images.githubusercontent.com/56406734/111543691-ce64b180-8749-11eb-9a49-55a979a7bd19.PNG)

---

This is the current file structure

<img src="https://user-images.githubusercontent.com/56406734/111543799-efc59d80-8749-11eb-926f-c94c214f51a2.PNG" alt="file structure" title="current file structure" width="300" height="1000" />

**Comment by vinamramunot-tech** [comment]
another place where I had to change the imports are:

File: training/dataset.py

```py
from clean_text import clean_text
```

File: training/train.py

```py
from dataset import VoiceDataset
from checkpoint import load_checkpoint, save_checkpoint, get_latest_checkpoint
from validate import validate
from utils import get_parameters, check_space
```

**Comment by BenAAndrew** [comment]
These imports are designed for the app which runs from the root directory, rather than running the commands manually like you have (not that this should be a problem). If you could open a PR with all the import changes you needed to make then I'll test it for the app and merge if everything is still working. This would be super helpful!

Also, I was unable to process the audio you sent me and I think its due to the fact it uses 2 channels rather than 1. I'll add a fix for this today

Yours:
![barac](https://user-images.githubusercontent.com/35925918/111623644-8a71bb00-87e2-11eb-87b6-0e9b70c7561d.PNG)

Mine:
![dave](https://user-images.githubusercontent.com/35925918/111623650-8cd41500-87e2-11eb-8295-7a858580c535.PNG)

**Comment by BenAAndrew** [comment]
@vinamramunot-tech I've developed a script to convert and compress the audio to the right format reducing your audio from 820MB -> 410MB. It's still having issues with loading it however so will continue investigating.

**Comment by vinamramunot-tech** [comment]
I will create the PR for the imports. Let me know if you want me to test something regarding audio conversion.

**Comment by vinamramunot-tech** [comment]
@BenAAndrew I am going to close this issue for now. As you said we can come back to discuss this at a later stage.
