### ISSUE TITLE
training/dataset.py masking dataset

### ISSUE THREAD

**Issue by brooklynbagel** [BenAAndrew/Voice-Cloning-App#55]
In reference to this issue brought up on Discord (https://discord.com/channels/833666557954883614/833666634232496179/872342667055493141)

> Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from training.utils import (
  File "/content/Voice-Cloning-App/training/utils.py", line 5, in <module>
    from dataset.clip_generator import CHARACTER_ENCODING
ModuleNotFoundError: No module named 'dataset.clip_generator'; 'dataset' is not a package

when trying to run `python training.py ...`

It looks like `training/dataset.py` is masking the package at `dataset/`. The top-level `dataset` is imported once, and `training.dataset.py` is also imported once

```bash
grep -n -R dataset training | grep import
training/utils.py:6:from dataset.clip_generator import CHARACTER_ENCODING
training/train.py:16:from training.dataset import VoiceDataset
```

I can think of two fixes:

1. On line 9 of `training/train.py`, change `sys.path.append(dirname(dirname(abspath(__file__))))` to `sys.path.insert(0, dirname(dirname(abspath(__file__))))`, giving the project root higher precedence than `training/`
2. Change the name of `training/dataset.py` to something that does not clash with `dataset/`

I'll be happy to apply the fix myself, just wanted feedback on what would preferred.

Attached is a minimal reproducible example if you want to see what's going on. Look at the code in `A/test.py` to see what's going on.

[import-test.zip](https://github.com/BenAAndrew/Voice-Cloning-App/files/6940109/import-test.zip)

**Comment by BenAAndrew** [comment]
I've renamed `dataset.py` to `voice_dataset.py`. Could you check if this has fixed the problem?

**Comment by brooklynbagel** [comment]
It's fixed
