### ISSUE TITLE
CUDA capability sm_86 is not compatible with the current PyTorch installation

### ISSUE THREAD

**Issue by GuusDeKroon** [BenAAndrew/Voice-Cloning-App#60]
This error appears on my A6000 GPU running the software; I've already reinstalled CUDA and Torch to the appropriate versions.

`UserWarning: NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.`

**Comment by BenAAndrew** [comment]
Hi @GuusDeKroon, This is an issue I'm aware of at the moment and trying to fix. 

In the meanwhile, you can checkout the `cuda-11-1` branch and do a [manual install](https://github.com/BenAAndrew/Voice-Cloning-App/blob/main/install.md#manual-install-linux-windows)/. This should fix the problem

**Comment by BenAAndrew** [comment]
Could you try this exe: https://drive.google.com/file/d/1MILElFD-KohYFtwHGYI2YtElyeJutvow/view?usp=sharing

**Comment by GuusDeKroon** [comment]
Hi! I haven't encountered any issues using this version :)

**Comment by BenAAndrew** [comment]
Latest release (0.9.5) now supports 30 series GPU's
