### ISSUE TITLE
HTTP 503 Error when attempting to build a new dataset

### ISSUE THREAD

**Issue by RayDAnt3D** [BenAAndrew/Voice-Cloning-App#70]
Keep getting the following error in version 0.9.7 soon after attempting to build a new dataset in the Windows binary release:

> Type: HTTPError
Text: HTTP Error 503: Service Temporarily Unavailable
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 99, in create_dataset_post File "dataset\transcribe.py", line 113, in create_transcription_model File "dataset\transcribe.py", line 86, in __init__ File "torch\hub.py", line 364, in load File "torch\hub.py", line 393, in _load_local File "C:\Users\gbase/.cache\torch\hub\snakers4_silero-models_master\hubconf.py", line 27, in silero_stt **kwargs) File "C:\Users\gbase/.cache\torch\hub\snakers4_silero-models_master\utils.py", line 128, in init_jit_model progress=True) File "torch\hub.py", line 419, in download_url_to_file File "urllib\request.py", line 223, in urlopen File "urllib\request.py", line 532, in open File "urllib\request.py", line 642, in http_response File "urllib\request.py", line 570, in error File "urllib\request.py", line 504, in _call_chain File "urllib\request.py", line 650, in http_error_default urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by Vanceagher** [comment]
I have the same issue

**Comment by BenAAndrew** [comment]
Sorry I've only just seen this (I've been off for a week).

This issue is due to the fact that it downloads silero from torch.hub which doesn't work for some people (possibly firewall or region related)
I'm looking into solutions to package the exe with the required model so that the download is not needed.
