### ISSUE TITLE
Low batch size issue

### ISSUE THREAD

**Issue by gabcodedev** [BenAAndrew/Voice-Cloning-App#74]
My pc has 16 GB of RAM. If I try to use a batch size like 16 it starts training and after 10 iterations it throws a Cuda oom error.
and if I try something like 22 it throws a Cuda oom error and obviously doesn't even start training.

Is this the expected behavior?

**Comment by BenAAndrew** [comment]
Training does not use RAM but rather your GPU memory (called VRAM). If you are getting a CUDA OOM error you need to decrease the batch size until it starts working (i.e. 14 -> 12 -> 10 etc.)

**Comment by BenAAndrew** [comment]
Sorry for the late reply, hope that helps :)
