### ISSUE TITLE
'File not found' error when exporting a voice model with app on external SSD.

### ISSUE THREAD

**Issue by RayDAnt3D** [BenAAndrew/Voice-Cloning-App#77]
Keep getting the following error when attempting to export a voice model on a windows binary build of VCA **being run off of an external SSD**:

> Type: FileNotFoundError
Text: [Errno 2] No such file or directory: 'C:\\Users\\RayDAnt3D\\AppData\\Local\\Temp\\_MEI233922\\data\\models\\Test Voice Model 11\\checkpoint_9515'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 419, in download_model File "flask\helpers.py", line 629, in send_file FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\RayDAnt3D\\AppData\\Local\\Temp\\_MEI233922\\data\\models\\Test Voice Model 11\\checkpoint_9515'

**Comment by BenAAndrew** [comment]
Hi @RayDAnt3D, could you verify whether a fil exists at 'C:\Users\RayDAnt3D\AppData\Local\Temp\_MEI233922\data\models\Test Voice Model 11\checkpoint_9515'

**Comment by BenAAndrew** [comment]
Could you try on your C: drive just to make sure the issue is due to being on an external drive & not something else

**Comment by BenAAndrew** [comment]
Closing as no response was given to question & without further detail no action can be taken

**Comment by RayDAnt3D** [comment]
@BenAAndrew Sorry! Somehow missed notifications for your last question.

Moving/running the VCA executable to the C: drive results in the same behavior:

> Type: FileNotFoundError
Text: [Errno 2] No such file or directory: 'C:\\Users\\RayDAnt\\AppData\\Local\\Temp\\_MEI246242\\data\\models\\TestVCAProject\\checkpoint_16000'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 441, in download_model File "flask\helpers.py", line 629, in send_file FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\RayDAnt\\AppData\\Local\\Temp\\_MEI246242\\data\\models\\TestVCAProject\\checkpoint_16000'

Have found that creating this expected but non-existent directory ("C:\Users\RayDAnt\AppData\Local\Temp\_MEI246242\data\models\TestVCAProject\") and copying the checkpoint file to be exported to it works as a workaround to get the export process to complete.
