### ISSUE TITLE
Synthesis failure due to inclusion of illegal characters in 'results' temp folder tree and filenames.

### ISSUE THREAD

**Issue by RayDAnt3D** [BenAAndrew/Voice-Cloning-App#78]
Attempting to synthesize the following:
>"This is an example sentence that fails due to quotation marks."

Results in the following error:
> Type: OSError
Text: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'data\\results\\2021-10\\11-10-2021_23-56-22-"This_is_an_example_'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 315, in synthesis_post File "os.py", line 220, in makedirs OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'data\\results\\2021-10\\11-10-2021_23-56-22-"This_is_an_example_'

Similarly, attempting to synthesize the following:
>Hello there.
Hello friend.

In the paragraph mode results in the following error:
>Type: OSError
Text: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'data\\results\\2021-10\\12-10-2021_00-04-58-Hello_there.\r\nHello_'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 315, in synthesis_post File "os.py", line 220, in makedirs OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'data\\results\\2021-10\\12-10-2021_00-04-58-Hello_there.\r\nHello_'

**Comment by BenAAndrew** [comment]
Should be fixed in 1.0.3. Please reopen this if not
