### ISSUE TITLE
All unlabeled clips unplayable in the Manage datasets interface for a freshly built dataset.

### ISSUE THREAD

**Issue by RayDAnt3D** [BenAAndrew/Voice-Cloning-App#81]
This is with VCA release 1.0.2 using the compiled executable on Windows 10.
The play option is simply grayed out for all listed clips. Have checked, and all the listed clips **are** playable from within file explorer, and in the case of this dataset, ranging in length from 1-6 seconds.

**Comment by BenAAndrew** [comment]
I have a new release coming soon that fixes an issue with the unlabelled clips. If this doesn't help please let me know

**Comment by RayDAnt3D** [comment]
Just built a new dataset in 1.0.3 (using pre-built binary release under Windows 10) and still getting the same erroneous behavior - all listed unlabeled clips for the dataset in the dataset management page have their playback controls grayed out.

**Comment by BenAAndrew** [comment]
Have you tried force reloading the page to clear cache? It uses javascript to load the audio so you'll need to reload the javascript for that to work

**Comment by RayDAnt3D** [comment]
@BenAAndrew tried force reloading to no avail. All listed Unlabeled clips in the dropdown still have playback abilities completely grayed out and no clip length shown.

**Comment by RayDAnt3D** [comment]
Fwiw when navigating via File Explorer to the location of the unlabeled clips, all show up with their listed filenames in the app and they are playable via the system default app for wave files.

Although I did just notice that the subdirectory for unlabeled clips is named "unlabelled" the British way with two LL's. Which is something my U.S. spellchecker is wanting to correct. Wondering if there might be a spelling mismatch in the sourcecode somewhere...

**Comment by RayDAnt3D** [comment]
Popped open Console in Chrome, and am immediately getting the following error readout as soon as a dataset generated with unlabeled clip support is selected:
![Screenshot 2021-11-26 022917](https://user-images.githubusercontent.com/82961628/143543323-2896e38a-04a7-4a82-87f5-9bf195c025e3.png)

**Comment by BenAAndrew** [comment]
This should be fixed in 1.0.4. Please reopen if this is not the case

**Comment by RayDAnt3D** [comment]
@BenAAndrew 
Can't reopen issue (don't have permissions for that) but erroneous behavior persists unchanged in release 1.0.4.
