### ISSUE TITLE
AssertionError: Invalid characters in text (missing from language)

### ISSUE THREAD

**Issue by ssjenforcer** [BenAAndrew/Voice-Cloning-App#85]
What is this? 
It happens every time I try to upload a database to train.

" ߂,ȷ,ɜ,տ,̾,͡,ί,ַ,˲,¼,փ,ͧ,鍃,ژ,↔,а,ƶ,ɋ,אּ,貃,ߴ,ȭ,á,藺,߼,ہ,߶,   ,֣,ƴ,ڀ,ϫ,э,ͦ,ԭ,䊯,䚤,͚,ք,,≰,˦,ԋ,ƽ,α,숓,♦,↨,ӥ,΄,♂,ڵ,♥,ᄯ,è,ҕ,ן,͌,͎,ԩ,ܺ,،,ș,ї,ۮ,ͬ,ݍ,ڸ,⌂,ޔ,ʐ,ѽ,ծ,綝,䄖,䟛,֡,ԫ,淾,č,ԡ,ԉ,¶,ڞ,►,♫,޻,֠,޿,捭,ǜ,ܖ,§,ј,▼,ϛ,ۺ,⒱,۴,샊,,ǁ,͗,٨,ݐ,¬,↕,ս,ҏ, ,լ,춱,ó,袻,鐮,ӟ,ͼ,ǟ,р,ҩ,ղ,䤪,ׯ,˂,֐,ؖ,ܢ,؜,ͭ,ϧ,ԑ,̇,,ߪ,˝,ٶ,з,ʔ,ա,â,㖛,ڒ,ʍ,ⱀ,ԍ,ƕ,٠,˼,ً,☻,⎻,☺,ĳ,ܵ,ۤ,ϋ,̚,ѭ,҄,䎎,ٮ,ƣ,؃,ǐ,ħ,׌,ڌ,ÿ,ͳ,ȣ,ϣ,ؐ,󋫫,ƈ,ʏ,§,ӄ,ɵ,п,ٲ,ӧ,׶,ğ,ك,ә,נ,ߐ ,՜,ԏ,¥,♠,ǡ,ı,▬,䅎,ʤ,ܕ,ܞ,ص,̵,ɯ,♣,‼,ǭ,→,ú,ܦ,ȟ,͹,ĸ,˰,ى,҅,,◄,ä,δ,冭,֌,ّ,ɔ,ف,ƫ,م,ż,´,ҿ,♀,ޠ,ȓ,ځ,υ,߄,ĥ,ҷ,ϗ,ҝ,ұ,ް,̻,ޒ,ʑ,ފ,͍,۳,˴,,ӕ,é,ш,»,˃,ժ,←,̳,߬,̍,⇧,ґ,ݔ,؅,ᜓ,ؾ,۶,η,,烺,ǹ,б,څ,߫,,ʘ,☼,ط,ϟ,ԛ,я,ȑ,↑,ɮ,ˉ,ჲ,ꌝ,ܻ,鴌,ӹ,∟,շ,ғ,򧶳,̉,򭲽,ǖ,ٱ,د,ڜ,ѯ,▲,ö,ॵ,斒,ӝ,̱  ,˩,ۡ,ޡ,ʎ,ъ,﹬,ѓ,↓,ƅ,΅,׵,ތ,õ,ܹ,,ۓ,ٹ,֭,ƌ,ͅ,۾,է,ġ,ۄ,ѱ,⦮,ݒ,џ,ʊ,ƃ,đ,ޮ"

This is what it says

**Comment by BenAAndrew** [comment]
Just to be clear, the message is `Invalid characters in text (missing from language):` and then that list of symbols

**Comment by ssjenforcer** [comment]
Yes.  It says that.
Also, when it tries to upload the voice/text data it says something along the lines of "data sent NONE".

**Comment by ssjenforcer** [comment]
I tried again with the script saved as .doc and it says:

AssertionError: Invalid characters in text (missing from language): ▬,  ,‼,◄,ࡱ,☺,→,♀,♥,▼,♠,↓,↕,☻,♦, ,▲,►,↑,←,↨,∟,՜,♂,¶,☼,♣,,♫,↔,§
in browser

sending packet ping data NONE

**Comment by BenAAndrew** [comment]
Using a txt file for what worked?

**Comment by ssjenforcer** [comment]
> Using a txt file for what worked?

The upload for the voice dialogue script.
When I tried .doc and .odt formats they gave me that error.  But using a .txt file worked.
But it only sorted half my recorded dialogue, and my training model was very poor.

**Comment by BenAAndrew** [comment]
That would explain it, the text file must be .txt.
If you need help with the quality please join the discord where others may be able to help
