### ISSUE TITLE
Data being saved to temp directory

### ISSUE THREAD

**Issue by RayDAnt3D** [BenAAndrew/Voice-Cloning-App#87]
Attempting to export a voice model results in the following error:

> Type: FileNotFoundError
Text: [Errno 2] No such file or directory: 'C:\Users\RayDAnt\AppData\Local\Temp\_MEI246242\data\models\TestVCAProject\checkpoint_16000'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 441, in download_model File "flask\helpers.py", line 629, in send_file FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\RayDAnt\AppData\Local\Temp\_MEI246242\data\models\TestVCAProject\checkpoint_16000'

Regardless of where the VCA app and user files are located. Have found that manually copying the appropriate voice model checkpoint file to the location in the error (in this case "C:\Users\RayDAnt\AppData\Local\Temp_MEI246242\data\models\TestVCAProject") works as a workaround to get the export process to complete.

See also #77

**Comment by BenAAndrew** [comment]
Are you running the app from `C:\Users\RayDAnt\AppData\Local\Temp_MEI246242`?

**Comment by RayDAnt3D** [comment]
No. From `C:\Users\gbase\Downloads\VCA`

**Comment by BenAAndrew** [comment]
Hmm, could you try moving the exe to a new folder in your Documents? It should be creating a folder called `data` and saving all files to that folder

**Comment by RayDAnt3D** [comment]
Tried running it from `c:\VCA` and although it **does** generate a local `\data\` subdirectory tree there (which is where I have the voice model I'm attempting to export) the same error is popping up:

> Type: FileNotFoundError
Text: [Errno 2] No such file or directory: 'C:\\Users\\RayDAnt\\AppData\\Local\\Temp\\_MEI193922\\data\\models\\TestVCAProject\\checkpoint_16000'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 448, in download_model File "flask\helpers.py", line 629, in send_file FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\gbase\\RayDAnt\\Local\\Temp\\_MEI193922\\data\\models\\TestVCAProject\\checkpoint_16000'

**Comment by BenAAndrew** [comment]
Is the happening when you try to train? If so is your voice called `TestVCAProject` and do you have any files within `data/TestVCAProject`?

**Comment by RayDAnt3D** [comment]
This is happening post training upon selecting any Checkpoint listed for any Voice in the "Export Model" section of the Import/Export interface. Fwiw the "Dataset Export" section functions perfectly - including for the Datasets used to generate the voice models that fail to export.

**Comment by BenAAndrew** [comment]
Think I've figured it out and I've added a fix with 1.1.0, thanks for your help 😄
