### ISSUE TITLE
Alphabet file does not seem to be used in Google Colab

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [BenAAndrew/Voice-Cloning-App#94]
Hi,

Great project ! I post my comment here as an issue instead of [there](https://github.com/BenAAndrew/Voice-Cloning-App/issues/93) as a comment because it deals with the Colab training page specifically.

So on the Colab training page, I followed the instructions regarding the alphabet file, and I created a "French.txt" file in `Voice-Cloning/alphabets` folder based on `German.txt` [alphabet](https://github.com/BenAAndrew/Voice-Cloning-App/tree/main/alphabets). The alphabet is found  because it is selected in the drop-down list but then I get the "Invalid characters in text" error even though the characters listed in the error are present in "French.txt" alphabet file.

To make the training work I had to clone this repo, modify `DEFAULT_ALPHABET` in training's `__init__` module (code changes made directly in Colab were not taken into account). Consequently it seems that the custom made alphabet file is not used or I made something wrong.

**Comment by BenAAndrew** [comment]
Good spot, I'll get that fixed now

**Comment by BenAAndrew** [comment]
That should be fixed now, please reopen if not.
(P.S. You can download alphabet files from https://coqui.ai/ rather than creating yourself)

**Comment by Ca-ressemble-a-du-fake** [comment]
I'll check it out thanks for the fix! Regarding alphabet file, Coqui adds also very weird characters like ("ờ‐―₽→∆ɔɛ") so I don't feel so confident using them (I don't know if these added chars will bloat the memory consumption). Anyway thanks for the tip.
