### ISSUE TITLE
Cannot use "mount drive" icon on Colab notebook

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [BenAAndrew/Voice-Cloning-App#95]
Hi,

Usually when using Colab, I like to mount Google drive once and for all by clicking the icon on the left  upper corner of the screen. But here with the Voice Cloning notebook, this is not allowed. When I click the icon, it tells me "Run this cell to mount your Google Drive", and every time I restart/reset the notebook I have to go through the "Log In / Allow this app to access your Drive" process. I tried to delete the "Drive mount" cell but it keeps reappearing. How can I allow the use of "mount drive" icon ?

**Comment by BenAAndrew** [comment]
Not sure to be honest. You may need to make a copy of the notebook first.
I have not configured any custom restrictions that should prevent that from working if it's the norm

**Comment by Ca-ressemble-a-du-fake** [comment]
I did make a copy. Knowing that you did not add custom restrictions I'll enquire and find where it comes from. It's the first time I encounter this.

**Comment by Ca-ressemble-a-du-fake** [comment]
It looks like when I remove all the "GUI" components (widgets, sliders, ...) the problem disappears.

**Comment by BenAAndrew** [comment]
Closing as I don't think this is a problem within my control but rather an issue with colab
